Models/Classes/Current.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MvcOnlineTicariOtomasyon.Models.Classes
{
    public class Current
    {
        [Key]
        public int CurrentId { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        [Required(ErrorMessage ="Bu alanı boş geçemezsiniz.")]
        public string CurrentName { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        [Required(ErrorMessage = "Bu alanı boş geçemezsiniz.")]
        public string CurrentLastName { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        [Required(ErrorMessage = "Bu alanı boş geçemezsiniz.")]
        public string CurrentCity { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        [Required(ErrorMessage = "Bu alanı boş geçemezsiniz.")]
        public string CurrentMail { get; set; }
        public bool Status { get; set; }
        public ICollection<SalesMovement> SalesMovements { get; set; }
    }
}

Controllers/CurrentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyon.Models.Classes;


namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class CurrentController : Controller
    {
        // GET: Current
        Context context = new Context();
        public ActionResult Index()
        {
            var result = context.Currents.Where(x=>x.Status==true).ToList();
            return View(result);
        }
        [HttpGet]
        public ActionResult AddCurrent()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddCurrent(Current current)
        {
            current.Status = true;
            context.Currents.Add(current);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DeleteCurrent(int id)
        {
            var result = context.Currents.Find(id);
            result.Status = false;
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult GetCurrent(int id)
        {
            var result = context.Currents.Find(id);
            return View("GetCurrent",result);
        }
        public ActionResult UpdateCurrent(Current current)
        {
            if (!ModelState.IsValid)
            {
                return View("GetCurrent");
            }
            var result = context.Currents.Find(current.CurrentId);
            result.CurrentName = current.CurrentName;
            result.CurrentLastName = current.CurrentLastName;
            result.CurrentCity = current.CurrentCity;
            result.CurrentMail = current.CurrentMail;
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult CustomerSale(int id)
        {
            var result = context.SalesMovements.Where(x => x.CurrentId == id).ToList();
            var cr = context.Currents.Where(x => x.CurrentId == id).Select(y => y.CurrentName + " " + y.CurrentLastName).FirstOrDefault();
            ViewBag.cari = cr;
            return View(result);
        }
    }
}

Views/Current/AddCurrent.cshtml
@model MvcOnlineTicariOtomasyon.Models.Classes.Current 
@{
    ViewBag.Title = "AddCurrent";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>AddCurrent</h2>
<div class="container" style="margin-left:10px;">
    <h2>Yeni Cari Sayfası</h2>
    <br />
    <form class="form-group" method="post">
        @Html.Label("Cari Adı")
        @Html.TextAreaFor(x => x.CurrentName, new { @class = "form-control" })
        <br />
        @Html.Label("Cari Soyadı")
        @Html.TextAreaFor(x => x.CurrentLastName, new { @class = "form-control" })
        <br />
        @Html.Label("Cari Şehir")
        @Html.TextAreaFor(x => x.CurrentCity, new { @class = "form-control" })
        <br />
        @Html.Label("Cari Mail")
        @Html.TextAreaFor(x => x.CurrentMail, new { @class = "form-control" })
        <br />
        <button class="btn btn-info">Kaydet</button>
    </form>
</div>

Views/Current/CustomerSale.cshtml
@using MvcOnlineTicariOtomasyon.Models.Classes
@model List<SalesMovement>
@{
    ViewBag.Title = "CustomerSale";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br>
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Cari Adı: @ViewBag.cari</li>
</ol>

<table class="table table-condensed">
    <tr>
        <th>Satış Id</th>
        <th>Ürün</th>
        <th>Personel</th>
        <th>Fiyat</th>
        <th>Adet</th>
        <th>Toplam</th>
        <th>Tarih</th>
        <th>Yazdır</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.SaleId</td>
            <td>@item.Product.ProductName</td>
            <td>@item.Staff.StaffName @item.Staff.StaffLastName</td>
            <td>@item.Price</td>
            <td>@item.Piece</td>
            <td>@item.TotalAmount</td>
            <td>@item.Date</td>
            <td><a href="#" class="btn btn-info">Yazdır</a></td>
        </tr>
    }

</table>

Views/Current/GetCurrent.cshtml
@model MvcOnlineTicariOtomasyon.Models.Classes.Current
@{
    ViewBag.Title = "GetCurrent";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br/>
<h2>Cari GÜncelleme Ekranı</h2>
@using (Html.BeginForm("UpdateCurrent", "Current",FormMethod.Post))
{
<div class="form-group">
    @Html.HiddenFor(x => x.CurrentId)
    @Html.Label("Ad")
    @Html.TextAreaFor(x => x.CurrentName, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CurrentName, "", new { @style = "color:red" })
    <br />
    @Html.Label("Soyad")
    @Html.TextAreaFor(x => x.CurrentLastName, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CurrentLastName, "", new { @style = "color:red" })
    <br />
    @Html.Label("Şehir")
    @Html.TextAreaFor(x => x.CurrentCity, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CurrentCity, "", new { @style = "color:red" })
    <br />
    @Html.Label("Mail")
    @Html.TextAreaFor(x => x.CurrentMail, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CurrentMail, "", new { @style = "color:red" })
    <br />
    <button class="btn btn-default" style="background-color:yellowgreen"> Güncelle</button>
</div>
}

Views/Current/Index.cshtml
@using MvcOnlineTicariOtomasyon.Models.Classes
@model List<Current>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Index</h2>
<br/>

<table class="table table-striped">
    <tr>
        <th>Cari Id</th>
        <th>Ad</th>
        <th>Soyad</th>
        <th>Şehir</th>
        <th>Mail</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Detaylar</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.CurrentId</td>
            <td>@item.CurrentName</td>
            <td>@item.CurrentLastName</td>
            <td>@item.CurrentCity</td>
            <td>@item.CurrentMail</td>
            <td><a href="/Current/DeleteCurrent/@item.CurrentId" class="btn btn-danger">Sil</a></td>
            <td><a href="/Current/GetCurrent/@item.CurrentId" class="btn btn-warning">Güncelle</a></td>
            <td><a href="/Current/CustomerSale/@item.CurrentId" class="btn btn-default" style="background-color:lightcoral">Satış Geçmişi</a></td>
        </tr>
    }
</table>
<a href="/Current/AddCurrent/" class="btn btn-info"> Yeni Cari Ekle</a>