Controllers/BillController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyon.Models.Classes;
namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class BillController : Controller
    {
        // GET: Bill
        Context context = new Context();
        public ActionResult Index()
        {
            var result = context.Invoices.ToList();
            return View(result);
        }
        [HttpGet]
        public ActionResult AddBill()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddBill(Invoice invoice)
        {
            context.Invoices.Add(invoice);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult GetBill(int id)
        {
            var result = context.Invoices.Find(id);
            return View("GetBill", result);
        }
        public ActionResult UpdateBill(Invoice ınvoice)
        {
            var result = context.Invoices.Find(ınvoice.InvoiceId);
            result.InvoiceSerialNo = ınvoice.InvoiceSerialNo;
            result.InvoiceOrderNo = ınvoice.InvoiceOrderNo;
            result.Date = ınvoice.Date;
            result.Time = ınvoice.Time;
            result.Deliver = ınvoice.Deliver;
            result.Receive = ınvoice.Receive;
            result.TaxAdministration = ınvoice.TaxAdministration;
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult BillDetail(int id)
        {
            var result = context.BillPens.Where(x => x.BillId == id).ToList();
            return View(result);
        }
        [HttpGet]
        public ActionResult NewPen()
        {
            return View();
        }
        public ActionResult NewPen(BillPen billPen)
        {
            context.BillPens.Add(billPen);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Views/Bill/AddBill.cshtml
@model MvcOnlineTicariOtomasyon.Models.Classes.Invoice
@{
    ViewBag.Title = "AddBill";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Yeni Fatura Sayfası</h2>

<div class="container" style="margin-left:10px;">
    <form class="form-group" method="post">
        <br />
        @Html.Label("Seri No")
        @Html.TextBoxFor(x => x.InvoiceSerialNo, new { @class = "form-control" })
        <br />
        @Html.Label("Sıra No")
        @Html.TextBoxFor(x => x.InvoiceOrderNo, new { @class = "form-control" })
        <br />
        @Html.Label("Tarih")
        @Html.TextBoxFor(x => x.Date, new { @class = "form-control" })
        <br />
        @Html.Label("Saat")
        @Html.TextBoxFor(x => x.Time, new { @class = "form-control" }) 
        <br />
        @Html.Label("Teslim Eden")
        @Html.TextBoxFor(x => x.Deliver, new { @class = "form-control" }) 
        <br />
        @Html.Label("Teslim Alan")
        @Html.TextBoxFor(x => x.Receive, new { @class = "form-control" })

        <button class="btn btn-sm" style="background-color:yellow; color:red;">Ürün Ekle</button>
    </form>
</div>

Views/Bill/BillDetail.cshtml
@using MvcOnlineTicariOtomasyon.Models.Classes
@model List<BillPen>
@{
    ViewBag.Title = "BillDetail";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Fatura Kalemleri Sayfası</h2>
<br />
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active"></li>
</ol>

<br />
<table class="table table-hover">
    <tr>
        <th>Personel Id</th>
        <th>Açıklama</th>
        <th>Miktar</th>
        <th>Birim Fiyat</th>
        <th>Tutar</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.BillPenId</td>
            <td>@item.Description</td>
            <td>@item.Quantity</td>
            <td>@item.UnitPrice</td>
            <td>@item.Amount</td>            
        </tr>
    }
</table>
<a href="/Bill/NewPen" class="btn btn-default" style="background-color:darksalmon"> Yeni Kalem Girişi</a>

Views/Bill/GetBill.cshtml
@model MvcOnlineTicariOtomasyon.Models.Classes.Invoice
@{
    ViewBag.Title = "GetBill";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Ürün Güncelleme Sayfası</h2>

@using (Html.BeginForm("UpdateBill", "Bill", FormMethod.Post))
{
<div class="container" style="margin-left:10px;">
    @Html.HiddenFor(x => x.InvoiceId)
    <br />
    @Html.Label("Seri No")
    @Html.TextBoxFor(x => x.InvoiceSerialNo, new { @class = "form-control" })
    <br />
    @Html.Label("Sıra No")
    @Html.TextBoxFor(x => x.InvoiceOrderNo, new { @class = "form-control" })
    <br />
    @Html.Label("Vegi Dairesi")
    @Html.TextBoxFor(x => x.TaxAdministration, new { @class = "form-control" })
    <br />
    @Html.Label("Tarih")
    @Html.TextBoxFor(x => x.Date, new { @class = "form-control" })
    <br />
    @Html.Label("Saat")
    @Html.TextBoxFor(x => x.Time, new { @class = "form-control" })
    <br />
    @Html.Label("Teslim Eden")
    @Html.TextBoxFor(x => x.Deliver, new { @class = "form-control" })

    <br />
    @Html.Label("Teslim Alan")
    @Html.TextBoxFor(x => x.Receive, new { @class = "form-control" })
    <button class="btn btn-sm" style="background-color:yellow; color:red;">Güncelle</button>

</div>
}

Views/Bill/Index.cshtml
@using MvcOnlineTicariOtomasyon.Models.Classes
@model List<Invoice>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<table class="table table-bordered" style="margin-top:20px; margin-left:20px;">
    <tr>
        <th>Id</th>
        <th>Seri no</th>
        <th>Sıra No</th>
        <th>Veri Dairesi</th>
        <th>Tarih</th>
        <th>Saat</th>
        <th>Teslim Eden</th>
        <th>Teslim Alan</th>
        <th>Güncelle</th>
        <th>Detaylar</th>
        <th>Toplam</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.InvoiceId</td>
            <td>@x.InvoiceSerialNo</td>
            <td>@x.InvoiceOrderNo</td>
            <td>@x.Date</td>
            <td>@x.Time</td>
            <td>@x.Time</td>
            <td>@x.Deliver</td>
            <td>@x.Receive</td>
            <td>@x.Total</td>

            <td>
                <a href="/Bill/GetBill/@x.InvoiceId" class="btn btn-warning">Güncelle</a>
            </td>
            <td>
                <a href="/Bill/BillDetail/@x.InvoiceId" class="btn btn-success">Detaylar</a>
            </td>

        </tr>
    }
</table>
<a href="/Bill/AddBill" class="btn btn-primary">Fatura Ekle</a>

Views/Bill/NewPen.cshtml
@model MvcOnlineTicariOtomasyon.Models.Classes.BillPen
@{
    ViewBag.Title = "NewPen";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Yeni Kalem Sayfası</h2>

<div class="container" style="margin-left:10px;">
    <form class="form-group" method="post">
        <br />
        @Html.Label("Açıklama")
        @Html.TextBoxFor(x => x.Description, new { @class = "form-control" })
        <br />
        @Html.Label("Miktar")
        @Html.TextBoxFor(x => x.Quantity, new { @class = "form-control" }) 
        <br />
        @Html.Label("Birim fiyat")
        @Html.TextBoxFor(x => x.UnitPrice, new { @class = "form-control" })
        <br />
        @Html.Label("Tutar")
        @Html.TextBoxFor(x => x.Amount, new { @class = "form-control" })
        <br />
        @Html.Label("Fatura Id")
        @Html.TextBoxFor(x => x.BillId, new { @class = "form-control" })
       

        <button class="btn btn-sm" style="background-color:yellow; color:red;">Ürün Ekle</button>
    </form>
</div>