Models/Classes/Staff.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MvcOnlineTicariOtomasyon.Models.Classes
{
    public class Staff
    {
        [Key]
        public int StaffId { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string StaffName { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string StaffLastName { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(250)]
        public string StaffImage { get; set; }

        public int DepartmentId { get; set; }
        public virtual Department Department { get; set; }
    }
}

Controllers/StaffController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyon.Models.Classes;

namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class StaffController : Controller
    {
        // GET: Staff
        Context context = new Context();
        public ActionResult Index()
        {
            var result = context.Staffs.ToList();
            return View(result);
        }
        [HttpGet]
        public ActionResult AddStaff()
        {
            List<SelectListItem> deger1 = (from x in context.Departments.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.DepartmentName,
                                               Value = x.DepartmentId.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;
            return View();
        }
        [HttpPost]
        public ActionResult AddStaff(Staff staff)
        {
            var result = context.Staffs.Add(staff);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult GetStaff(int id)
        {
            List<SelectListItem> deger1 = (from x in context.Departments.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.DepartmentName,
                                               Value = x.DepartmentId.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;
            var result = context.Staffs.Find(id);
            return View("GetStaff", result);
        }
        public ActionResult UpdateStaff(Staff staff)
        {
            var result = context.Staffs.Find(staff.StaffId);
            result.StaffName = staff.StaffName;
            result.StaffLastName = staff.StaffLastName;
            result.StaffImage = staff.StaffImage;
            result.DepartmentId = staff.DepartmentId;
            context.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

Views/Staff/AddStaff.cshtml
@model MvcOnlineTicariOtomasyon.Models.Classes.Staff
@{
    ViewBag.Title = "AddStaff";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h2>Yeni Personel Sayfası</h2>
<div class="container" style="margin-left:10px;">
    <form class="form-group" method="post">
        <br />
        @Html.Label("Personel Adı")
        @Html.TextBoxFor(x => x.StaffName, new { @class = "form-control" })
        <br />
        @Html.Label("Personel Soyad")
        @Html.TextBoxFor(x => x.StaffLastName, new { @class = "form-control" })
        <br />
        @Html.Label("Personel Görsel")
        @Html.TextBoxFor(x => x.StaffImage, new { @class = "form-control" })
        <br />
        @Html.Label("Departman")
        @Html.DropDownListFor(x=>x.DepartmentId,(List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control"})
        <br />
        <button class="btn btn-sm" style="background-color:yellow; color:red;">Ürün Ekle</button>
    </form>
</div>

Views/Staff/GetStaff.cshtml
@model MvcOnlineTicariOtomasyon.Models.Classes.Staff
@{
    ViewBag.Title = "GetStaff";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Personel GÜncelleme Ekranı</h2>
@using (Html.BeginForm("UpdateStaff", "Staff", FormMethod.Post))
{
<div class="form-group">
    @Html.HiddenFor(x => x.StaffId)
    @Html.Label("Ad")
    @Html.TextAreaFor(x => x.StaffName, new { @class = "form-control" })
    <br />
    @Html.Label("Soyad")
    @Html.TextAreaFor(x => x.StaffLastName, new { @class = "form-control" })
    <br />
    @Html.Label("Görsel")
    @Html.TextAreaFor(x => x.StaffImage, new { @class = "form-control" })
    <br />
    @Html.Label("Departman")
    @Html.DropDownListFor(x => x.DepartmentId, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" }))
    <br />
    <button class="btn btn-default" style="background-color:yellowgreen"> Güncelle</button>
</div>
}

Views/Staff/Index.cshtml
@using MvcOnlineTicariOtomasyon.Models.Classes
@model List<Staff>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Index</h2>
<table class="table table-bordered" style="margin-top:20px; margin-left:20px;">
    <tr>
        <th>Id</th>
        <th>Personel Adı</th>
        <th>Soyad</th>
        <th>Görsel</th>
        <th>Departman</th>
        <th>Güncelle</th>
        <th>Satışlar</th>
    </tr>
    @foreach (var staff in Model)
    {
        <tr>
            <td> @staff.StaffId</td>
            <td> @staff.StaffName</td>
            <td> @staff.StaffLastName</td>
            <td> @staff.StaffImage</td>
            <td> @staff.Department.DepartmentName</td>
            <td> <a href="/Staff/GetStaff/@staff.StaffId" class="btn btn-warning">Güncelle</a></td>
            <td> <a href="/Department/DepartmentStaffSales/@staff.StaffId" class="btn btn-success"> Detaylar</a></td>

        </tr>
    }
</table>
<a href="/Staff/AddStaff" class="btn btn-primary">Personel Ekle</a>